var classes = [
    {
        "name": "App\\CacheKernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 7,
        "lloc": 4,
        "mi": 213.45,
        "mIwoC": 171,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\DefaultController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 118.9,
        "mIwoC": 73.16,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logoutCheck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 2,
        "length": 16,
        "vocabulary": 9,
        "volume": 50.72,
        "difficulty": 1.86,
        "effort": 94.19,
        "level": 0.54,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 27.31,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 17,
        "loc": 30,
        "lloc": 13,
        "mi": 109.45,
        "mIwoC": 63.49,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\Task",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 120,
        "vocabulary": 33,
        "volume": 605.33,
        "difficulty": 8.93,
        "effort": 5404.71,
        "level": 0.11,
        "bugs": 0.2,
        "time": 300,
        "intelligentContent": 67.8,
        "number_operators": 20,
        "number_operands": 100,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 58,
        "loc": 115,
        "lloc": 57,
        "mi": 85.84,
        "mIwoC": 41.28,
        "commentWeight": 44.56,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 0.47,
        "relativeSystemComplexity": 400.47,
        "totalStructuralComplexity": 2400,
        "totalDataComplexity": 2.81,
        "totalSystemComplexity": 2402.81,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\Security\\Core\\Security",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Form\\DataTransferObject\\PasswordUpdate",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 118,
        "vocabulary": 30,
        "volume": 579.01,
        "difficulty": 9.6,
        "effort": 5558.53,
        "level": 0.1,
        "bugs": 0.19,
        "time": 309,
        "intelligentContent": 60.31,
        "number_operators": 22,
        "number_operands": 96,
        "number_operators_unique": 5,
        "number_operands_unique": 25,
        "cloc": 52,
        "loc": 105,
        "lloc": 53,
        "mi": 85.9,
        "mIwoC": 41.56,
        "commentWeight": 44.34,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.46,
        "relativeSystemComplexity": 324.46,
        "totalStructuralComplexity": 1620,
        "totalDataComplexity": 2.32,
        "totalSystemComplexity": 1622.32,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\AppFixtures",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataFixture",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addUsers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addTasks",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Persistence\\ObjectManager",
            "Symfony\\Component\\Yaml\\Yaml",
            "Doctrine\\Persistence\\ObjectManager",
            "App\\Entity\\User",
            "Doctrine\\Persistence\\ObjectManager",
            "App\\Entity\\Task",
            "DateTime"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 72,
        "vocabulary": 29,
        "volume": 349.77,
        "difficulty": 4.96,
        "effort": 1734.88,
        "level": 0.2,
        "bugs": 0.12,
        "time": 96,
        "intelligentContent": 70.52,
        "number_operators": 10,
        "number_operands": 62,
        "number_operators_unique": 4,
        "number_operands_unique": 25,
        "cloc": 32,
        "loc": 70,
        "lloc": 38,
        "mi": 90.5,
        "mIwoC": 47.19,
        "commentWeight": 43.31,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.15,
        "relativeSystemComplexity": 256.15,
        "totalStructuralComplexity": 1024,
        "totalDataComplexity": 0.59,
        "totalSystemComplexity": 1024.59,
        "package": "App\\DataFixtures\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Task",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "urlIsDoneValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 5,
        "wmc": 14,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Datetime",
            "Datetime"
        ],
        "parents": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 10,
        "volume": 152.81,
        "difficulty": 3.63,
        "effort": 553.93,
        "level": 0.28,
        "bugs": 0.05,
        "time": 31,
        "intelligentContent": 42.15,
        "number_operators": 17,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 77,
        "loc": 143,
        "lloc": 66,
        "mi": 90.11,
        "mIwoC": 44.75,
        "commentWeight": 45.36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11.38,
        "relativeSystemComplexity": 11.38,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 148,
        "totalSystemComplexity": 148,
        "package": "App\\Entity\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoles",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEqualTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 4,
        "wmc": 14,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\User\\EquatableInterface"
        ],
        "parents": [],
        "lcom": 3,
        "length": 47,
        "vocabulary": 12,
        "volume": 168.49,
        "difficulty": 7,
        "effort": 1179.45,
        "level": 0.14,
        "bugs": 0.06,
        "time": 66,
        "intelligentContent": 24.07,
        "number_operators": 19,
        "number_operands": 28,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 128,
        "loc": 200,
        "lloc": 72,
        "mi": 90.9,
        "mIwoC": 43.62,
        "commentWeight": 47.28,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 6.19,
        "relativeSystemComplexity": 7.19,
        "totalStructuralComplexity": 13,
        "totalDataComplexity": 80.5,
        "totalSystemComplexity": 93.5,
        "package": "App\\Entity\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Event\\PasswordHashSubscriber",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prePersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "preUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hashPassword",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Common\\EventSubscriber",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Persistence\\Event\\LifecycleEventArgs",
            "Doctrine\\ORM\\Event\\PreUpdateEventArgs"
        ],
        "parents": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 8,
        "volume": 69,
        "difficulty": 5.1,
        "effort": 351.9,
        "level": 0.2,
        "bugs": 0.02,
        "time": 20,
        "intelligentContent": 13.53,
        "number_operators": 6,
        "number_operands": 17,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 23,
        "loc": 54,
        "lloc": 31,
        "mi": 96.56,
        "mIwoC": 54.19,
        "commentWeight": 42.37,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 36.54,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 2.71,
        "totalSystemComplexity": 182.71,
        "package": "App\\Event\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Event\\TaskSubscriber",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prePersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Common\\EventSubscriber",
            "Symfony\\Component\\Security\\Core\\Security",
            "Doctrine\\Persistence\\Event\\LifecycleEventArgs",
            "DateTime"
        ],
        "parents": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 6,
        "effort": 398.63,
        "level": 0.17,
        "bugs": 0.02,
        "time": 22,
        "intelligentContent": 11.07,
        "number_operators": 8,
        "number_operands": 12,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 20,
        "loc": 42,
        "lloc": 22,
        "mi": 101.39,
        "mIwoC": 57.55,
        "commentWeight": 43.84,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 16.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 49.6,
        "package": "App\\Event\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\DataTransferObject\\PasswordUpdate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getActualPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setActualPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNewPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setNewPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConfirmPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setConfirmPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 24,
        "vocabulary": 6,
        "volume": 62.04,
        "difficulty": 3.75,
        "effort": 232.65,
        "level": 0.27,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 16.54,
        "number_operators": 9,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 48,
        "loc": 82,
        "lloc": 34,
        "mi": 100.24,
        "mIwoC": 53.91,
        "commentWeight": 46.33,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.5,
        "relativeSystemComplexity": 6.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 39,
        "totalSystemComplexity": 39,
        "package": "App\\Form\\DataTransferObject\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Form\\TaskType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 9,
        "volume": 34.87,
        "difficulty": 0,
        "effort": 0,
        "level": 1.64,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 9,
        "loc": 21,
        "lloc": 12,
        "mi": 107.98,
        "mIwoC": 65.52,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\AbstractUserForm",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "getRolesOptions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transformRolesType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\Form\\CallbackTransformer"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 31,
        "vocabulary": 13,
        "volume": 114.71,
        "difficulty": 2.09,
        "effort": 239.86,
        "level": 0.48,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 54.86,
        "number_operators": 8,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 17,
        "loc": 40,
        "lloc": 23,
        "mi": 97.95,
        "mIwoC": 55.6,
        "commentWeight": 42.34,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "package": "App\\Form\\User\\",
        "pageRank": 0.09,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\AccountType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Form\\User\\AbstractUserForm",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "App\\Form\\User\\AbstractUserForm"
        ],
        "lcom": 2,
        "length": 18,
        "vocabulary": 12,
        "volume": 64.53,
        "difficulty": 0.77,
        "effort": 49.86,
        "level": 1.29,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 83.51,
        "number_operators": 1,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 11,
        "loc": 27,
        "lloc": 16,
        "mi": 102.56,
        "mIwoC": 60.79,
        "commentWeight": 41.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\UpdatePasswordType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 16,
        "vocabulary": 11,
        "volume": 55.35,
        "difficulty": 0.75,
        "effort": 41.51,
        "level": 1.33,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 73.8,
        "number_operators": 1,
        "number_operands": 15,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 103.39,
        "mIwoC": 61.87,
        "commentWeight": 41.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\UserType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Form\\User\\AbstractUserForm",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "App\\Form\\User\\AbstractUserForm"
        ],
        "lcom": 2,
        "length": 24,
        "vocabulary": 20,
        "volume": 103.73,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0.03,
        "time": 0,
        "intelligentContent": 172.88,
        "number_operators": 0,
        "number_operands": 24,
        "number_operators_unique": 0,
        "number_operands_unique": 20,
        "cloc": 10,
        "loc": 23,
        "lloc": 13,
        "mi": 104.1,
        "mIwoC": 61.45,
        "commentWeight": 42.64,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "registerBundles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProjectDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureContainer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel",
            "class",
            "Symfony\\Component\\DependencyInjection\\ContainerBuilder",
            "Symfony\\Component\\Config\\Loader\\LoaderInterface",
            "Symfony\\Component\\Config\\Resource\\FileResource",
            "Symfony\\Component\\Routing\\RouteCollectionBuilder"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "lcom": 1,
        "length": 99,
        "vocabulary": 33,
        "volume": 499.4,
        "difficulty": 9.02,
        "effort": 4504.16,
        "level": 0.11,
        "bugs": 0.17,
        "time": 250,
        "intelligentContent": 55.37,
        "number_operators": 32,
        "number_operands": 67,
        "number_operators_unique": 7,
        "number_operands_unique": 26,
        "cloc": 0,
        "loc": 37,
        "lloc": 37,
        "mi": 46.09,
        "mIwoC": 46.09,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 25.29,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 101.17,
        "package": "App\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\TaskRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findTasks",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filterTasks",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry",
            "Doctrine\\ORM\\QueryBuilder",
            "Doctrine\\ORM\\QueryBuilder"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 2,
        "length": 33,
        "vocabulary": 15,
        "volume": 128.93,
        "difficulty": 4.73,
        "effort": 609.47,
        "level": 0.21,
        "bugs": 0.04,
        "time": 34,
        "intelligentContent": 27.27,
        "number_operators": 7,
        "number_operands": 26,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 27,
        "loc": 49,
        "lloc": 22,
        "mi": 101.31,
        "mIwoC": 55.67,
        "commentWeight": 45.64,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 100.3,
        "totalStructuralComplexity": 300,
        "totalDataComplexity": 0.91,
        "totalSystemComplexity": 300.91,
        "package": "App\\Repository\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Repository\\UserRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findAllExceptOne",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 9,
        "volume": 34.87,
        "difficulty": 0.63,
        "effort": 21.79,
        "level": 1.6,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 55.79,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 16,
        "loc": 28,
        "lloc": 12,
        "mi": 111.58,
        "mIwoC": 65.52,
        "commentWeight": 46.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 49.25,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 98.5,
        "package": "App\\Repository\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Security\\Guard\\LoginFormAuthenticator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLoginUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onAuthenticationSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\User\\UserProviderInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfToken",
            "Symfony\\Component\\Security\\Core\\Exception\\InvalidCsrfTokenException",
            "Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException",
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator"
        ],
        "lcom": 3,
        "length": 79,
        "vocabulary": 27,
        "volume": 375.64,
        "difficulty": 6.82,
        "effort": 2561.16,
        "level": 0.15,
        "bugs": 0.13,
        "time": 142,
        "intelligentContent": 55.09,
        "number_operators": 19,
        "number_operands": 60,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 46,
        "loc": 100,
        "lloc": 54,
        "mi": 86.9,
        "mIwoC": 43.51,
        "commentWeight": 43.39,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.87,
        "relativeSystemComplexity": 64.87,
        "totalStructuralComplexity": 448,
        "totalDataComplexity": 6.11,
        "totalSystemComplexity": 454.11,
        "package": "App\\Security\\Guard\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Security\\Voter\\TaskVoter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 35,
        "vocabulary": 16,
        "volume": 140,
        "difficulty": 6.6,
        "effort": 924,
        "level": 0.15,
        "bugs": 0.05,
        "time": 51,
        "intelligentContent": 21.21,
        "number_operators": 13,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 16,
        "loc": 42,
        "lloc": 26,
        "mi": 94.15,
        "mIwoC": 53.3,
        "commentWeight": 40.85,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 30.75,
        "package": "App\\Security\\Voter\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Security\\Voter\\UserVoter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 15,
        "volume": 117.21,
        "difficulty": 6.33,
        "effort": 742.31,
        "level": 0.16,
        "bugs": 0.04,
        "time": 41,
        "intelligentContent": 18.51,
        "number_operators": 11,
        "number_operands": 19,
        "number_operators_unique": 6,
        "number_operands_unique": 9,
        "cloc": 16,
        "loc": 41,
        "lloc": 25,
        "mi": 95.53,
        "mIwoC": 54.35,
        "commentWeight": 41.18,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 30.75,
        "package": "App\\Security\\Voter\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Service\\Cache\\HttpCacheValidation",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Service\\Cache\\CacheValidationInterface",
            "Symfony\\Component\\HttpFoundation\\RequestStack",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 6,
        "volume": 38.77,
        "difficulty": 5.5,
        "effort": 213.26,
        "level": 0.18,
        "bugs": 0.01,
        "time": 12,
        "intelligentContent": 7.05,
        "number_operators": 4,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 11,
        "loc": 29,
        "lloc": 18,
        "mi": 102.02,
        "mIwoC": 61.23,
        "commentWeight": 40.79,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 51,
        "package": "App\\Service\\Cache\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Validator\\MatchPassword",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\Validator\\Constraint"
        ],
        "parents": [
            "Symfony\\Component\\Validator\\Constraint"
        ],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 7,
        "loc": 12,
        "lloc": 5,
        "mi": 217.29,
        "mIwoC": 171,
        "commentWeight": 46.29,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Validator\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Validator\\MatchPasswordValidator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Component\\Validator\\ConstraintValidator",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Validator\\Constraint",
            "Symfony\\Component\\Validator\\Exception\\UnexpectedValueException",
            "Symfony\\Component\\Validator\\Exception\\LogicException"
        ],
        "parents": [
            "Symfony\\Component\\Validator\\ConstraintValidator"
        ],
        "lcom": 1,
        "length": 32,
        "vocabulary": 14,
        "volume": 121.84,
        "difficulty": 5.83,
        "effort": 710.71,
        "level": 0.17,
        "bugs": 0.04,
        "time": 39,
        "intelligentContent": 20.89,
        "number_operators": 11,
        "number_operands": 21,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 12,
        "loc": 37,
        "lloc": 25,
        "mi": 92.7,
        "mIwoC": 54.09,
        "commentWeight": 38.61,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Validator\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    }
]