var classes = [
    {
        "name": "App\\Controller\\DefaultController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 10,
        "loc": 18,
        "lloc": 8,
        "mi": 118.9,
        "mIwoC": 73.16,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logoutCheck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 2,
        "length": 8,
        "vocabulary": 6,
        "volume": 20.68,
        "difficulty": 0.7,
        "effort": 14.48,
        "level": 1.43,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 29.54,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 17,
        "loc": 28,
        "lloc": 11,
        "mi": 114.67,
        "mIwoC": 67.94,
        "commentWeight": 46.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TaskController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "App\\Repository\\TaskRepository",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\Task",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "App\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 125,
        "vocabulary": 33,
        "volume": 630.55,
        "difficulty": 9.46,
        "effort": 5967.7,
        "level": 0.11,
        "bugs": 0.21,
        "time": 332,
        "intelligentContent": 66.62,
        "number_operators": 19,
        "number_operands": 106,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 58,
        "loc": 115,
        "lloc": 57,
        "mi": 85.72,
        "mIwoC": 41.15,
        "commentWeight": 44.56,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 441,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 441.45,
        "totalStructuralComplexity": 2646,
        "totalDataComplexity": 2.68,
        "totalSystemComplexity": 2648.68,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 12,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Service\\Cache\\CacheValidationInterface",
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Form\\DataTransferObject\\PasswordUpdate",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "lcom": 1,
        "length": 117,
        "vocabulary": 27,
        "volume": 556.32,
        "difficulty": 8.26,
        "effort": 4595.7,
        "level": 0.12,
        "bugs": 0.19,
        "time": 255,
        "intelligentContent": 67.34,
        "number_operators": 22,
        "number_operands": 95,
        "number_operators_unique": 4,
        "number_operands_unique": 23,
        "cloc": 54,
        "loc": 108,
        "lloc": 54,
        "mi": 86.37,
        "mIwoC": 41.91,
        "commentWeight": 44.46,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 361.43,
        "totalStructuralComplexity": 1805,
        "totalDataComplexity": 2.15,
        "totalSystemComplexity": 1807.15,
        "package": "App\\Controller\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Task",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "urlIsDoneValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 5,
        "wmc": 14,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Datetime",
            "Datetime"
        ],
        "parents": [],
        "lcom": 1,
        "length": 48,
        "vocabulary": 11,
        "volume": 166.05,
        "difficulty": 3.44,
        "effort": 571.96,
        "level": 0.29,
        "bugs": 0.06,
        "time": 32,
        "intelligentContent": 48.21,
        "number_operators": 17,
        "number_operands": 31,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 77,
        "loc": 143,
        "lloc": 66,
        "mi": 89.86,
        "mIwoC": 44.49,
        "commentWeight": 45.36,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11.38,
        "relativeSystemComplexity": 11.38,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 148,
        "totalSystemComplexity": 148,
        "package": "App\\Entity\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoles",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEqualTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 4,
        "wmc": 14,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\User\\EquatableInterface"
        ],
        "parents": [],
        "lcom": 3,
        "length": 50,
        "vocabulary": 13,
        "volume": 185.02,
        "difficulty": 6.89,
        "effort": 1274.6,
        "level": 0.15,
        "bugs": 0.06,
        "time": 71,
        "intelligentContent": 26.86,
        "number_operators": 19,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 136,
        "loc": 208,
        "lloc": 72,
        "mi": 90.83,
        "mIwoC": 43.34,
        "commentWeight": 47.49,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 6.19,
        "relativeSystemComplexity": 7.19,
        "totalStructuralComplexity": 13,
        "totalDataComplexity": 80.5,
        "totalSystemComplexity": 93.5,
        "package": "App\\Entity\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Event\\PasswordHashSubscriber",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prePersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "preUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hashPassword",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Common\\EventSubscriber",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Persistence\\Event\\LifecycleEventArgs",
            "Doctrine\\ORM\\Event\\PreUpdateEventArgs"
        ],
        "parents": [],
        "lcom": 2,
        "length": 28,
        "vocabulary": 9,
        "volume": 88.76,
        "difficulty": 5,
        "effort": 443.79,
        "level": 0.2,
        "bugs": 0.03,
        "time": 25,
        "intelligentContent": 17.75,
        "number_operators": 8,
        "number_operands": 20,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 23,
        "loc": 57,
        "lloc": 34,
        "mi": 94.05,
        "mIwoC": 52.41,
        "commentWeight": 41.64,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 36.54,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 2.71,
        "totalSystemComplexity": 182.71,
        "package": "App\\Event\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Event\\TaskSubscriber",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prePersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Common\\EventSubscriber",
            "Symfony\\Component\\Security\\Core\\Security",
            "Doctrine\\Persistence\\Event\\LifecycleEventArgs",
            "DateTime"
        ],
        "parents": [],
        "lcom": 2,
        "length": 19,
        "vocabulary": 9,
        "volume": 60.23,
        "difficulty": 4.8,
        "effort": 289.1,
        "level": 0.21,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 12.55,
        "number_operators": 7,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 20,
        "loc": 42,
        "lloc": 22,
        "mi": 101.69,
        "mIwoC": 57.85,
        "commentWeight": 43.84,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 16.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 49.6,
        "package": "App\\Event\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\DataTransferObject\\PasswordUpdate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getActualPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setActualPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNewPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setNewPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConfirmPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setConfirmPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface",
            "App\\Form\\DataTransferObject\\PasswordInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 7,
        "volume": 75.8,
        "difficulty": 3.6,
        "effort": 272.87,
        "level": 0.28,
        "bugs": 0.03,
        "time": 15,
        "intelligentContent": 21.06,
        "number_operators": 9,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 49,
        "loc": 83,
        "lloc": 34,
        "mi": 99.72,
        "mIwoC": 53.3,
        "commentWeight": 46.42,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.5,
        "relativeSystemComplexity": 6.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 39,
        "totalSystemComplexity": 39,
        "package": "App\\Form\\DataTransferObject\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Form\\TaskType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 10,
        "volume": 46.51,
        "difficulty": 0,
        "effort": 0,
        "level": 1.43,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 14,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 9,
        "loc": 21,
        "lloc": 12,
        "mi": 107.1,
        "mIwoC": 64.65,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\AbstractUserForm",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "getRolesOptions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "transformRolesType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\Form\\CallbackTransformer"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 31,
        "vocabulary": 13,
        "volume": 114.71,
        "difficulty": 2.09,
        "effort": 239.86,
        "level": 0.48,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 54.86,
        "number_operators": 8,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 17,
        "loc": 40,
        "lloc": 23,
        "mi": 97.95,
        "mIwoC": 55.6,
        "commentWeight": 42.34,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "package": "App\\Form\\User\\",
        "pageRank": 0.11,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\AccountType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Form\\User\\AbstractUserForm",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "App\\Form\\User\\AbstractUserForm"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 14,
        "volume": 83.76,
        "difficulty": 0.81,
        "effort": 67.65,
        "level": 1.24,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 103.71,
        "number_operators": 1,
        "number_operands": 21,
        "number_operators_unique": 1,
        "number_operands_unique": 13,
        "cloc": 11,
        "loc": 27,
        "lloc": 16,
        "mi": 101.77,
        "mIwoC": 60,
        "commentWeight": 41.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\UpdatePasswordType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 14,
        "volume": 83.76,
        "difficulty": 0.81,
        "effort": 67.65,
        "level": 1.24,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 103.71,
        "number_operators": 1,
        "number_operands": 21,
        "number_operators_unique": 1,
        "number_operands_unique": 13,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 102.13,
        "mIwoC": 60.61,
        "commentWeight": 41.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\User\\UserType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Form\\User\\AbstractUserForm",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "App\\Form\\User\\AbstractUserForm"
        ],
        "lcom": 2,
        "length": 29,
        "vocabulary": 21,
        "volume": 127.38,
        "difficulty": 0,
        "effort": 0,
        "level": 1.45,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 184.48,
        "number_operators": 0,
        "number_operands": 29,
        "number_operators_unique": 0,
        "number_operands_unique": 21,
        "cloc": 10,
        "loc": 23,
        "lloc": 13,
        "mi": 103.47,
        "mIwoC": 60.83,
        "commentWeight": 42.64,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Form\\User\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Helper\\UrlManagerTrait",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "validReferer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 12,
        "vocabulary": 6,
        "volume": 31.02,
        "difficulty": 1,
        "effort": 31.02,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 31.02,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 21,
        "loc": 33,
        "lloc": 12,
        "mi": 112.83,
        "mIwoC": 65.61,
        "commentWeight": 47.22,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "App\\Helper\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Security\\Guard\\LoginFormAuthenticator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLoginUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onAuthenticationSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\User\\UserProviderInterface",
            "Symfony\\Component\\Security\\Csrf\\CsrfToken",
            "Symfony\\Component\\Security\\Core\\Exception\\InvalidCsrfTokenException",
            "Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException",
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Guard\\Authenticator\\AbstractFormLoginAuthenticator"
        ],
        "lcom": 3,
        "length": 75,
        "vocabulary": 26,
        "volume": 352.53,
        "difficulty": 6.79,
        "effort": 2392.19,
        "level": 0.15,
        "bugs": 0.12,
        "time": 133,
        "intelligentContent": 51.95,
        "number_operators": 18,
        "number_operands": 57,
        "number_operators_unique": 5,
        "number_operands_unique": 21,
        "cloc": 46,
        "loc": 98,
        "lloc": 52,
        "mi": 87.71,
        "mIwoC": 44.06,
        "commentWeight": 43.65,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 64.86,
        "totalStructuralComplexity": 448,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 454,
        "package": "App\\Security\\Guard\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 12,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Security\\Voter\\TaskVoter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 35,
        "vocabulary": 16,
        "volume": 140,
        "difficulty": 6.6,
        "effort": 924,
        "level": 0.15,
        "bugs": 0.05,
        "time": 51,
        "intelligentContent": 21.21,
        "number_operators": 13,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 18,
        "loc": 44,
        "lloc": 26,
        "mi": 95.12,
        "mIwoC": 53.3,
        "commentWeight": 41.83,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 30.75,
        "package": "App\\Security\\Voter\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Security\\Voter\\UserVoter",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 15,
        "volume": 117.21,
        "difficulty": 6.33,
        "effort": 742.31,
        "level": 0.16,
        "bugs": 0.04,
        "time": 41,
        "intelligentContent": 18.51,
        "number_operators": 11,
        "number_operands": 19,
        "number_operators_unique": 6,
        "number_operands_unique": 9,
        "cloc": 19,
        "loc": 44,
        "lloc": 25,
        "mi": 96.9,
        "mIwoC": 54.35,
        "commentWeight": 42.55,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 30.75,
        "package": "App\\Security\\Voter\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Service\\Cache\\HttpCacheValidation",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Service\\Cache\\CacheValidationInterface",
            "Symfony\\Component\\HttpFoundation\\RequestStack",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 8,
        "volume": 63,
        "difficulty": 4.5,
        "effort": 283.5,
        "level": 0.22,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 14,
        "number_operators": 6,
        "number_operands": 15,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 13,
        "loc": 33,
        "lloc": 20,
        "mi": 100.06,
        "mIwoC": 58.75,
        "commentWeight": 41.31,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 51,
        "package": "App\\Service\\Cache\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Validator\\MatchPassword",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\Validator\\Constraint"
        ],
        "parents": [
            "Symfony\\Component\\Validator\\Constraint"
        ],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 7,
        "loc": 12,
        "lloc": 5,
        "mi": 217.29,
        "mIwoC": 171,
        "commentWeight": 46.29,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Validator\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Validator\\MatchPasswordValidator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Component\\Validator\\ConstraintValidator",
            "Symfony\\Component\\Security\\Core\\Security",
            "Symfony\\Component\\Validator\\Constraint",
            "Symfony\\Component\\Validator\\Exception\\UnexpectedValueException"
        ],
        "parents": [
            "Symfony\\Component\\Validator\\ConstraintValidator"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 14,
        "volume": 118.03,
        "difficulty": 5.83,
        "effort": 688.5,
        "level": 0.17,
        "bugs": 0.04,
        "time": 38,
        "intelligentContent": 20.23,
        "number_operators": 10,
        "number_operands": 21,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 14,
        "loc": 37,
        "lloc": 23,
        "mi": 95.87,
        "mIwoC": 55.11,
        "commentWeight": 40.76,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Validator\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]